const quizData = [
    // ====================================================================
    // A. 40 SOAL DERET (Soal 1 - 40)
    // ====================================================================
    {
        question: "2, 4, 8, 16, 32, ?",
        a: "48",
        b: "54",
        c: "64",
        d: "72",
        e: "80",
        correct: "c",
    },
    {
        question: "5, 10, 20, 40, 80, ?",
        a: "100",
        b: "120",
        c: "150",
        d: "160",
        e: "200",
        correct: "d",
    },
    {
        question: "1, 4, 9, 16, 25, ?",
        a: "30",
        b: "35",
        c: "36",
        d: "42",
        e: "49",
        correct: "c",
    },
    {
        question: "3, 6, 12, 24, 48, ?",
        a: "60",
        b: "72",
        c: "90",
        d: "96",
        e: "108",
        correct: "d",
    },
    {
        question: "7, 14, 28, 56, 112, ?",
        a: "126",
        b: "224",
        c: "252",
        d: "280",
        e: "320",
        correct: "b",
    },
    {
        question: "80, 70, 60, 50, 40, ?",
        a: "35",
        b: "30",
        c: "25",
        d: "20",
        e: "10",
        correct: "b",
    },
    {
        question: "4, 9, 19, 39, 79, ?",
        a: "119",
        b: "159",
        c: "139",
        d: "149",
        e: "159",
        correct: "e",
    },
    {
        question: "100, 90, 81, 73, 66, ?",
        a: "60",
        b: "59",
        c: "58",
        d: "61",
        e: "55",
        correct: "a",
    },
    {
        question: "2, 3, 5, 8, 12, 17, ?",
        a: "23",
        b: "24",
        c: "25",
        d: "26",
        e: "27",
        correct: "a",
    },
    {
        question: "1, 2, 6, 24, 120, ?",
        a: "240",
        b: "360",
        c: "480",
        d: "720",
        e: "840",
        correct: "d",
    },
    {
        question: "10, 20, 40, 80, 160, ?",
        a: "200",
        b: "240",
        c: "280",
        d: "320",
        e: "400",
        correct: "d",
    },
    {
        question: "64, 32, 16, 8, 4, ?",
        a: "2",
        b: "3",
        c: "6",
        d: "8",
        e: "10",
        correct: "a",
    },
    {
        question: "9, 18, 27, 36, 45, ?",
        a: "50",
        b: "54",
        c: "56",
        d: "60",
        e: "63",
        correct: "b",
    },
    {
        question: "2, 5, 10, 17, 26, ?",
        a: "35",
        b: "37",
        c: "38",
        d: "40",
        e: "42",
        correct: "b",
    },
    {
        question: "3, 6, 11, 18, 27, ?",
        a: "34",
        b: "36",
        c: "38",
        d: "40",
        e: "42",
        correct: "c",
    },
    {
        question: "81, 64, 49, 36, 25, ?",
        a: "20",
        b: "16",
        c: "9",
        d: "4",
        e: "1",
        correct: "b",
    },
    {
        question: "1, 3, 7, 15, 31, ?",
        a: "47",
        b: "55",
        c: "63",
        d: "65",
        e: "71",
        correct: "c",
    },
    {
        question: "2, 4, 7, 11, 16, 22, ?",
        a: "27",
        b: "28",
        c: "29",
        d: "30",
        e: "31",
        correct: "c",
    },
    {
        question: "50, 45, 41, 38, 36, ?",
        a: "35",
        b: "34",
        c: "33",
        d: "32",
        e: "31",
        correct: "a",
    },
    {
        question: "5, 15, 45, 135, ?",
        a: "270",
        b: "405",
        c: "540",
        d: "675",
        e: "810",
        correct: "b",
    },
    {
        question: "1, 4, 13, 40, 121, ?",
        a: "243",
        b: "362",
        c: "364",
        d: "365",
        e: "370",
        correct: "c",
    },
    {
        question: "0, 1, 1, 2, 3, 5, 8, ?",
        a: "10",
        b: "11",
        c: "12",
        d: "13",
        e: "15",
        correct: "d",
    },
    {
        question: "100, 99, 97, 94, 90, ?",
        a: "85",
        b: "86",
        c: "84",
        d: "83",
        e: "82",
        correct: "a",
    },
    {
        question: "1, 8, 27, 64, 125, ?",
        a: "150",
        b: "200",
        c: "216",
        d: "225",
        e: "256",
        correct: "c",
    },
    {
        question: "6, 11, 21, 36, 56, ?",
        a: "70",
        b: "81",
        c: "91",
        d: "101",
        e: "111",
        correct: "b",
    },
    {
        question: "1, 2, 4, 8, 16, 32, 64, ?",
        a: "96",
        b: "100",
        c: "112",
        d: "128",
        e: "150",
        correct: "d",
    },
    {
        question: "0, 2, 6, 12, 20, 30, ?",
        a: "36",
        b: "40",
        c: "42",
        d: "45",
        e: "48",
        correct: "c",
    },
    {
        question: "2, 6, 18, 54, 162, ?",
        a: "324",
        b: "486",
        c: "512",
        d: "648",
        e: "729",
        correct: "b",
    },
    {
        question: "20, 17, 13, 8, 2, ?",
        a: "0",
        b: "-3",
        c: "-4",
        d: "-5",
        e: "-6",
        correct: "d",
    },
    {
        question: "1, 3, 9, 27, 81, ?",
        a: "162",
        b: "243",
        c: "324",
        d: "405",
        e: "486",
        correct: "b",
    },
    {
        question: "11, 22, 44, 88, 176, ?",
        a: "220",
        b: "264",
        c: "352",
        d: "400",
        e: "440",
        correct: "c",
    },
    {
        question: "10, 9, 7, 4, 0, ?",
        a: "-5",
        b: "-3",
        c: "-2",
        d: "1",
        e: "2",
        correct: "a",
    },
    {
        question: "1, 2, 6, 24, 120, 720, ?",
        a: "840",
        b: "960",
        c: "1024",
        d: "5040",
        e: "7200",
        correct: "d",
    },
    {
        question: "90, 80, 71, 63, 56, ?",
        a: "49",
        b: "50",
        c: "48",
        d: "46",
        e: "45",
        correct: "b",
    },
    {
        question: "2, 5, 11, 23, 47, ?",
        a: "94",
        b: "95",
        c: "96",
        d: "97",
        e: "98",
        correct: "b",
    },
    {
        question: "1, 4, 9, 16, 25, 36, ?",
        a: "42",
        b: "44",
        c: "49",
        d: "56",
        e: "64",
        correct: "c",
    },
    {
        question: "2, 6, 12, 20, 30, ?",
        a: "40",
        b: "42",
        c: "44",
        d: "46",
        e: "48",
        correct: "b",
    },
    {
        question: "10, 12, 17, 27, 42, ?",
        a: "50",
        b: "55",
        c: "60",
        d: "62",
        e: "67",
        correct: "d",
    },
    {
        question: "8, 16, 14, 28, 26, 52, ?",
        a: "48",
        b: "50",
        c: "54",
        d: "60",
        e: "62",
        correct: "b",
    },
    {
        question: "2, 3, 5, 9, 17, 33, ?",
        a: "49",
        b: "51",
        c: "57",
        d: "65",
        e: "66",
        correct: "d",
    },

    // ====================================================================
    // B. 20 SOAL LOGIKA (Soal 41 - 60)
    // ====================================================================
    {
        question: "Semua guru adalah pendidik. Semua pendidik adalah pekerja sosial. Sebagian pekerja sosial adalah relawan. Tidak ada relawan yang pemalas. Kesimpulan yang tepat:",
        a: "Semua guru adalah relawan.",
        b: "Sebagian guru bukan pemalas.",
        c: "Semua relawan guru.",
        d: "Semua guru pemalas.",
        e: "Tidak dapat disimpulkan.",
        correct: "b",
    },
    {
        question: "Semua mahasiswa suka belajar. Semua yang suka belajar membaca buku. Semua yang membaca buku pandai. Tidak semua mahasiswa pandai. Kesimpulan yang tepat:",
        a: "Semua mahasiswa pandai.",
        b: "Tidak ada mahasiswa yang pandai.",
        c: "Pernyataan saling bertentangan.",
        d: "Sebagian mahasiswa pandai.",
        e: "Tidak dapat disimpulkan.",
        correct: "c",
    },
    {
        question: "Semua dokter adalah manusia. Semua manusia makan. Semua yang makan butuh energi. Semua yang butuh energi hidup. Kesimpulan yang tepat:",
        a: "Semua manusia dokter.",
        b: "Semua dokter hidup.",
        c: "Semua yang hidup dokter.",
        d: "Sebagian manusia tidak makan.",
        e: "Tidak dapat disimpulkan.",
        correct: "b",
    },
    {
        question: "Semua burung bisa terbang. Semua elang adalah burung. Semua elang pemangsa. Tidak semua pemangsa burung. Kesimpulan yang tepat:",
        a: "Semua elang bisa terbang.",
        b: "Semua burung elang.",
        c: "Tidak ada burung yang pemangsa.",
        d: "Semua pemangsa bisa terbang.",
        e: "Tidak dapat disimpulkan.",
        correct: "a",
    },
    {
        question: "Semua siswa rajin belajar. Beberapa siswa tidak disiplin. Semua yang rajin belajar ingin sukses. Semua yang ingin sukses bekerja keras. Kesimpulan yang tepat:",
        a: "Semua siswa bekerja keras.",
        b: "Sebagian siswa bekerja keras.",
        c: "Tidak ada siswa yang bekerja keras.",
        d: "Semua siswa tidak disiplin.",
        e: "Tidak dapat disimpulkan.",
        correct: "b",
    },
    {
        question: "Semua kucing adalah hewan. Semua hewan bernapas. Semua yang bernapas hidup. Tidak semua yang hidup hewan. Kesimpulan yang tepat:",
        a: "Semua kucing hidup.",
        b: "Semua hewan kucing.",
        c: "Semua yang hidup hewan.",
        d: "Sebagian kucing tidak hidup.",
        e: "Tidak dapat disimpulkan.",
        correct: "a",
    },
    {
        question: "Semua dosen membaca buku. Semua yang membaca buku suka belajar. Semua yang suka belajar berilmu. Semua yang berilmu dihormati. Kesimpulan yang tepat:",
        a: "Semua dosen dihormati.",
        b: "Semua dosen tidak dihormati.",
        c: "Semua yang dihormati dosen.",
        d: "Sebagian dosen tidak berilmu.",
        e: "Tidak dapat disimpulkan.",
        correct: "a",
    },
    {
        question: "Semua guru wanita pendidik. Sebagian pendidik psikolog. Semua psikolog paham manusia. Semua guru wanita paham manusia. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Semua guru pria juga paham manusia.",
        e: "Sebagian guru wanita paham manusia.",
        correct: "c",
    },
    {
        question: "Semua ilmuwan suka berpikir. Semua pemikir cerdas. Semua cerdas kreatif. Semua ilmuwan kreatif. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian ilmuwan tidak kreatif.",
        e: "Semua kreatif ilmuwan.",
        correct: "a",
    },
    {
        question: "Semua mahasiswa psikologi suka menganalisis. Semua yang suka menganalisis logis. Semua yang logis rasional. Semua mahasiswa psikologi rasional. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian benar.",
        e: "Semua yang rasional mahasiswa psikologi.",
        correct: "a",
    },
    {
        question: "Semua pemimpin tegas. Semua yang tegas disegani. Semua yang disegani dihormati. Semua pemimpin dihormati. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian benar.",
        e: "Semua yang dihormati pemimpin.",
        correct: "a",
    },
    {
        question: "Semua ikan hidup di air. Semua paus hidup di air. Semua paus mamalia. Tidak semua mamalia hidup di air. Kesimpulan yang tepat:",
        a: "Semua mamalia paus.",
        b: "Semua paus hidup di air.",
        c: "Tidak ada paus yang mamalia.",
        d: "Sebagian mamalia ikan.",
        e: "Tidak dapat disimpulkan.",
        correct: "b",
    },
    {
        question: "Semua siswa SD suka bermain. Semua yang suka bermain ceria. Sebagian siswa SD rajin. Semua yang rajin disukai guru. Kesimpulan yang tepat:",
        a: "Semua siswa SD disukai guru.",
        b: "Sebagian siswa SD disukai guru.",
        c: "Tidak ada siswa SD disukai guru.",
        d: "Tidak dapat disimpulkan.",
        e: "Sebagian yang ceria disukai guru.",
        correct: "b",
    },
    {
        question: "Semua mahasiswa rajin membaca. Semua yang rajin membaca berpengetahuan luas. Semua yang berpengetahuan luas cerdas. Semua mahasiswa cerdas. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian benar.",
        e: "Semua yang cerdas mahasiswa.",
        correct: "a",
    },
    {
        question: "Semua pegawai hadir pagi. Semua yang hadir pagi disiplin. Semua yang disiplin berprestasi. Semua pegawai berprestasi. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian benar.",
        e: "Semua yang berprestasi pegawai.",
        correct: "a",
    },
    {
        question: "Semua pemain bola kuat. Semua yang kuat berlatih keras. Semua yang berlatih keras sehat. Semua pemain bola sehat. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian benar.",
        e: "Semua yang sehat pemain bola.",
        correct: "a",
    },
    {
        question: "Semua programmer suka logika. Semua yang suka logika suka matematika. Semua yang suka matematika pintar. Semua programmer pintar. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian benar.",
        e: "Semua yang pintar programmer.",
        correct: "a",
    },
    {
        question: "Semua polisi tegas. Semua yang tegas berani. Tidak semua berani polisi. Semua polisi berani. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian benar.",
        e: "Semua yang berani polisi.",
        correct: "a",
    },
    {
        question: "Semua dokter menjaga kesehatan. Semua yang menjaga kesehatan panjang umur. Semua dokter panjang umur. Semua panjang umur bahagia. Kesimpulan yang tepat:",
        a: "Semua dokter bahagia.",
        b: "Semua bahagia dokter.",
        c: "Sebagian dokter tidak bahagia.",
        d: "Tidak dapat disimpulkan.",
        e: "Sebagian yang bahagia dokter.",
        correct: "a",
    },
    {
        question: "Semua manusia berpikir. Semua yang berpikir berakal. Semua yang berakal beretika. Semua manusia beretika. Kesimpulan yang tepat:",
        a: "Benar.",
        b: "Salah.",
        c: "Tidak dapat disimpulkan.",
        d: "Sebagian benar.",
        e: "Semua yang beretika manusia.",
        correct: "a",
    }
];